<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\StellarAdmin.TagHelpers\StellarAdmin.TagHelpers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\AsChild\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step1.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step2.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step3.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step4.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step5.cshtml" />
    <_ContentIncludedByDefault Remove="Pages\AsChild\_Step6.cshtml" />
  </ItemGroup>
  <Target Name="Tailwind" BeforeTargets="Build">
    <Exec
      WorkingDirectory="Client"
      Command="npm install"
      Condition=" !Exists('Client/node_modules') "
    />
    <Exec
      Command="npx @tailwindcss/cli -i ./css/site.css -o ../wwwroot/css/site.css"
      WorkingDirectory="Client"
    />
  </Target>
</Project>
