namespace StellarAdmin.TagHelpers.Icons;

/*
The compiler chokes on the large files generated by the source generator. It seems to be
related to https://github.com/dotnet/roslyn/issues/81704. We can reconsider adding these
icons back once that is resolved, or move them out to separate NuGet packages
*/

/*public class TablerOutlineIconPack : IIconPack
{
    public IDictionary<string, IconDefinition> GetIcons()
    {
        return TablerOutlineIcons.IconDefinitions;
    }
}*/
