namespace StellarAdmin.TagHelpers.Icons;

/*
The compiler chokes on the large files generated by the source generator. It seems to be
related to https://github.com/dotnet/roslyn/issues/81704. We can reconsider adding these
icons back once that is resolved, or move them out to separate NuGet packages
*/

/*
internal static partial class TablerOutlineIcons
{
    private static readonly Dictionary<string, string> SvgAttributes = new Dictionary<
        string,
        string
    >
    {
        ["xmlns"] = "http://www.w3.org/2000/svg",
        ["width"] = "24",
        ["height"] = "24",
        ["viewBox"] = "0 0 24 24",
        ["fill"] = "none",
        ["stroke"] = "currentColor",
        ["stroke-width"] = "2",
        ["stroke-linecap"] = "round",
        ["stroke-linejoin"] = "round",
    };
}
*/
